### ISSUE TITLE
Update strips off build container tag

### ISSUE THREAD

**Issue by brian-mcnamara** [salesforce/dockerfile-image-update#35]
Docker multistage build allows you to have
`FROM alpine:latest as builder`
to reference the build container in a multi-stage build. However the updater appears to strip off the 'as builder' when updating.

**Comment by afalko** [comment]
Thanks for filing this @brian-mcnamara . A fix should be possible here by keeping track of any text after a space: https://github.com/salesforce/dockerfile-image-update/blob/05ff19cd2f2b18166c741e91804c10b1a1f9fe8d/dockerfile-image-update/src/main/java/com/salesforce/dockerfileimageupdate/utils/DockerfileGitHubUtil.java#L181

Let me know if you'd like to try making a PR, otherwise, I'll try to find some time to fix either later this week  or next.

**Comment by brian-mcnamara** [comment]
Thank @afalko , I have a PR ready. Ill link it.
